### ISSUE TITLE
Assembler: To-Do-List

### ISSUE THREAD

**Issue by zamlz** [zamlz/hummus-n-chips#1]
### List of features that need to be implemented. 
_(italics mean that it's not necessary)_

- [x] Write a Debug Function that utilizes debugging sets.
- [x] Create a DFA for preprocessing comments and whitespace.
- [x] Implement hummus plus header. Should only contain universal code utilized by simulator, assembler, and compiler. (misc_utils)
- [x] Generate Variable and Symbol table (first pass)
- [x] Implement second pass string-to-hex conversion.
